name: Trigger satis

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  trigger-satis-build:
      runs-on: ubuntu-latest
      steps:
        - name: Emit repository_dispatch for satis
          uses: mvasigh/dispatch-action@main
          with:
            token: ${{ secrets.GHCRPAT }}
            repo: satis
            owner: inlinestudio
            event_type: satisBuild